# - name: Задача deploy
#   command: "echo {{ test }}"
#   register: res
#   changed_when: "'0' not in res.stdout"

# - name: Циклы
#   debug:
#     msg: "{{ item }}"
#   loop:
#     - a
#     - b

# - name: Циклы
#   debug:
#     msg: "{{ item.name }} is {{ item.group }}"
#   loop:
#     - { name: "Вася", group: "admin"}
#     - { name: "Маша", group: "admin"}

# - name: Циклы
#   vars:
#     data:
#       a: 1
#       b: 2
#   debug:
#     msg: "{{ item.key }} is {{ item.value }}"
#   loop: "{{ data | dict2items }}"

# - name: Циклы
#   command: echo "{{ item }}"
#   loop:
#     - a
#     - b
#   register: res

# - name: Debug
#   debug:
#     var: res

# - name: Циклы
#   command: echo "{{ item }}"
#   loop:
#     - a
#     - b
#   register: res

# - name: Debug
#   debug:
#     var: res

# - name: Циклы
#   debug:
#     msg: "{{ item }}"
#   loop: "{{ groups['all'] }}"

# - name: Циклы
#   debug:
#     msg: "{{ item.name }}"
#   loop:
#     - name: "Вася"
#       group: "admin"
#       roles:
#         admin: true
#         manager: true
#         user: true
#   loop_control:
#     label: "{{ item.name }}"

# - name: Циклы
#   debug:
#     msg: "{{ item.name }}"
#   loop:
#     - name: "Вася"
#     - name: "Катя"
#     - name: "Антон"
#   loop_control:
#     pause: 3

# - name: Циклы
#   debug:
#     msg: "{{ item.name }} - {{ my_indx }}"
#   loop:
#     - name: "Вася"
#     - name: "Катя"
#     - name: "Антон"
#   loop_control:
#     index_var: my_indx

# - name: Циклы
#   debug:
#     msg: "{{ item.name }} - {{ ansible_loop.allitems }}"
#   loop:
#     - name: "Вася"
#     - name: "Катя"
#     - name: "Антон"
#   loop_control:
#     extended: yes

# - name: Циклы
#   ansible.builtin.include_tasks: inner.yml
#   loop:
#     - name: "Вася"
#     - name: "Катя"
#     - name: "Антон"
#   loop_control:
#     loop_var: outer_loop

# - name: Задача deploy
#   debug:
#     msg: "{{ lookup('file', '../meta/main.yml') }}"

# - name: Задача deploy
#   debug:
#     msg: "{{ lookup('file', '../meta/mains.yml', errors='warn') }}"

# - name: Задача deploy
#   debug:
#     msg: "{{ lookup('file', 'main.yml', errors='warn') }}"

# - name: Задача deploy
#   vars:
#     my_name: a
#   debug:
#     msg: "{{ lookup('vars', 'my_name') }}"

# - name: Задача deploy
#   debug:
#     msg: "{{ my_var | default(5) }}"

# - name: Задача deploy
#   file:
#     dest: "{{ item.path }}"
#     state: touch
#     mode: "{{ item.mode | default(omit) }}"
#   loop:
#     - path: "/test"
#     - path: "/test2"
#       mode: "0666"

# - name: Задача deploy
#   vars:
#     admin: true
#   debug:
#    msg: "{{ admin | type_debug }}"

# - name: Задача deploy
#   vars:
#     admin:
#       - key: a
#         value: 1
#       - key: b
#         value: 2
#   debug:
#     msg: "{{ admin | items2dict }}"

# - name: Задача deploy
#   vars:
#     admin:
#       - keys: a
#         values: 1
#       - keys: b
#         values: 2
#   debug:
#    msg: "{{ admin | items2dict(key_name='keys', value_name='values') }}"

# - name: Задача deploy
#   vars:
#     admin: "true"
#   debug:
#     msg: "{{ admin | bool }}"

# - name: Задача deploy
#   vars:
#     admin: { a: 1, b: 2 }
#   debug:
#     msg: "{{ admin | to_nice_yaml }}"

# - name: Задача deploy
#   vars:
#     admin: { a: 1, b: 2 }
#   debug:
#     msg: "{{ admin | combine({'c': 3}) }}"

# - name: Задача deploy
#   vars:
#     admin: [1, 2, 3]
#   debug:
#     msg: "{{ admin | zip(['a', 'b', 'c']) }}"

# - name: Задача deploy
#   vars:
#     admin: [1, 2]
#   debug:
#     msg: "{{ admin | map('extract', ['a', 'b', 'c']) | list }}"

# - name: Задача deploy
#   vars:
#     admin: ['1', '2']
#   debug:
#     msg: "{{ admin | join(',') }}"

# - name: Задача deploy
#   vars:
#     admin: [1, 2]
#   debug:
#     msg: "{{ admin | random }}"

# - name: Задача deploy
#   vars:
#     admin: [1, [2, 3]]
#   debug:
#     msg: "{{ admin | flatten }}"

# - name: Задача deploy
#   vars:
#     admin: [1, [2, 3], [3, 4]]
#   debug:
#     msg: "{{ admin | flatten | unique}}"

# - name: Задача deploy
#   vars:
#     admin: [1, 2, 3]
#   debug:
#     msg: "{{ admin | intersect([1, 2])}}"

# - name: Задача deploy
#   vars:
#     admin: [1, 2, 3]
#   debug:
#     msg: "{{ admin | union([1, 2, 4])}}"

- name: "Создание сети"
  community.docker.docker_network:
    name: "{{ deploy_network_name }}"
    driver: overlay

- name: "Выкладка сервисов"
  vars:
    service_name: "{{ item.name }}"
    version: "{{ item.version }}"
  ansible.builtin.include_tasks:
    file: "../services/{{ item.name }}/service.yml"
    apply:
      tags: "{{ item.name }}"
  tags: always
  loop: "{{ services }}"
