- name: Deploy / Build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: ssh_users
      tags: ssh_users
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    # - deploy
    # - swarm_init
- name: Manager
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join
