galaxy_info:
  role_name: preconfig
  description: Cоздание пользователей, генерация публичного и приватного SSH ключа
  author: Max Lartsev
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
