---
- name: "[{{ service_name }}] Выкладка сервиса"
  block:
    - name: "[{{ service_name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        image: "{{ registry_name }}{{ service_name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ deploy_network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3001
            target_port: 80
  tags: "{{ service_name }}"
