galaxy_info:
  role_name: deploy
  description: Выкладка микросервисов на Docker кластер
  author: Max Lartsev
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
allow_duplicates: true
