- name: "[{{ service_name }}] Конфигурация секрета"
  block:
    - name: "[{{ service_name }}] Создаем секрет"
      ansible.builtin.include_tasks: "secret-create.yml"
  tags: "{{ service_name }}"

  rescue:
    - name: "[{{ service_name }}] Удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        state: absent
    - name: "[{{ service_name }}] Создаем секрет"
      ansible.builtin.include_tasks: "secret-create.yml"
