- name: Установка Docker
  become: true
  block:
    - name: Добавляем universe
      ansible.builtin.apt_repository:
        repo: "deb http://ports.ubuntu.com/ubuntu-ports/ {{ ansible_distribution_release }} universe"
        state: present
      # tags: universe

    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-docker
        update-cache: true
        cache_valid_time: 86400

    - name: Создание папки keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Добавление ключа Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Установка стабильного репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Установка Docker-ce
      ansible.builtin.apt:
        name: docker-ce
        update-cache: true

    - name: Проверка что Docker установлен и перезагружен
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

- name: Установка Docker Compose
  become: true
  block:
    - name: Получение последней версии Docker Compose
      ansible.builtin.uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: preconfig_page

    - name: Установка Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ preconfig_page.json.tag_name }}/docker-compose-linux-aarch64"
        dest: /usr/local/bin/docker_compose
        mode: "0755"

# - name: Настройка дополнительных пакетов Python
#   block:
#     - name: Установка pip пакетов
#       ansible.builtin.pip:
#         name: docker

- name: Завершение установки
  become: true
  block:
    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Перезагрузка сервера
      ansible.builtin.reboot:
        msg: Rebooting...
        reboot_timeout: 100
