---
- name: "[{{ service_name }}] Выкладка сервиса"
  block:
    - name: "[{{ service_name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        image: "rabbitmq:3-management"
        state: present
        networks:
          - name: "{{ deploy_network_name }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}

  tags: "{{ service_name }}"
